name: Rathna Workflow
on:
  push:
       workflow_dispatch:
jobs:  
       Hello-Rathna:
                  runs-on: ubuntu_latest
     steps:
      - name: Hello Rathna
        run: echo "Hello Rathna"
